<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CRUDsuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f6cb84f1-011d-4cba-972c-8985aca0671d</testSuiteGuid>
   <testCaseLink>
      <guid>2bf9c4ad-25ff-45b9-b651-30a314f0f0fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>2d5f5842-ccf4-46c0-a9b7-ee725f3d2aa1</id>
         <masked>false</masked>
         <name>gender</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Input User Biodata</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>908aa5a6-b295-49c9-af71-affd81561f64</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data User/Biodata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>908aa5a6-b295-49c9-af71-affd81561f64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>first_name</value>
         <variableId>18925786-2656-4ab3-b2ab-bccb582d891d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>908aa5a6-b295-49c9-af71-affd81561f64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>last_name</value>
         <variableId>8cbd1bce-70dc-48ef-8403-2cef16ca2e38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>908aa5a6-b295-49c9-af71-affd81561f64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>684f072e-bfa0-4036-91a7-8ebbea7c0a20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>908aa5a6-b295-49c9-af71-affd81561f64</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>gender</value>
         <variableId>2d5f5842-ccf4-46c0-a9b7-ee725f3d2aa1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
