<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save and go to list</name>
   <tag></tag>
   <elementGuidId>a8563320-8eb6-4477-8bff-78a6e04bfe46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d9e90db-d5e9-4441-af76-66a54be2ad81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat btn-info btn_save btn_action btn_save_back</value>
      <webElementGuid>f28f5e45-4e24-4781-9e54-0e7ea5ec6eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_save</value>
      <webElementGuid>c4308842-9ebd-441b-a5b2-3b22569dd1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stype</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>43681104-320b-47a6-8ce5-5a7918f6edd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Save and go to list (Ctrl+d)</value>
      <webElementGuid>9b352463-557d-49bc-8fbe-5852b981901c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip888095</value>
      <webElementGuid>ad857269-f6f1-4ca2-987a-dd88d77d8cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Save and go to list                            </value>
      <webElementGuid>f0840df2-4f7b-4a37-a591-6549b776626d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_userbiodata&quot;)/div[@class=&quot;row-fluid col-md-7 container-button-bottom&quot;]/a[@id=&quot;btn_save&quot;]</value>
      <webElementGuid>66f13399-3b8e-4cef-be6b-2bd63f18e26c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_save']</value>
      <webElementGuid>5b4738b0-072b-4bfa-a594-4ba6a35afbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_userbiodata']/div[7]/a</value>
      <webElementGuid>1887d946-2fab-4155-9d51-1b7603d81970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/following::a[1]</value>
      <webElementGuid>183724ab-c85d-4219-aa45-714c19dbcb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and go to list (Ctrl+d)'])[1]/preceding::a[1]</value>
      <webElementGuid>ad097835-9648-4f1c-9912-535763ec019c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save and go to list']/parent::*</value>
      <webElementGuid>56a7cc1e-b98e-45dd-95ee-3b2ca62cf087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a</value>
      <webElementGuid>c129e836-fe58-443e-9709-a5e27b271559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_save' and (text() = '
                                 Save and go to list                            ' or . = '
                                 Save and go to list                            ')]</value>
      <webElementGuid>9636487d-529b-48f1-a5d9-fd22f55dbbdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
