<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_photo</name>
   <tag></tag>
   <elementGuidId>fec3e4c5-975b-4990-85bf-00a487fe1a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='qqfile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;qqfile&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d11cf473-06bc-4686-8982-2472fc0aa477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>qq-button-id</name>
      <type>Main</type>
      <value>c0087ed4-ba36-485d-a61c-b673dc7b9090</value>
      <webElementGuid>791426e2-22c9-4e82-8d8a-cefdf70a2332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>file input</value>
      <webElementGuid>f99ba1b9-3a34-4b20-8e8b-cc3d93e28d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>2c6fc50b-0ded-4d3f-a85d-02ceb6d557b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qqfile</value>
      <webElementGuid>608ece15-a8b8-49f7-900e-d8f42278b9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userbiodata_photo_galery&quot;)/div[@class=&quot;qq-new-skin shadow qq-upload-image-placeholder  qq-uploader-selector qq-uploader qq-gallery&quot;]/div[@class=&quot;qq-upload-button-selector qq-upload-button qq-upload-button-hover qq-upload-button-focus&quot;]/input[1]</value>
      <webElementGuid>6f8c6e81-72c7-4112-b662-bf54a84871e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='qqfile']</value>
      <webElementGuid>d2a3a9b1-28fc-4fc9-bf19-9cbc912983d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userbiodata_photo_galery']/div/div[3]/input</value>
      <webElementGuid>5a1f588b-4dd3-4241-b4f6-1a71bf27c271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4b9e6302-61a6-471f-97fd-1fea9fa24f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'file input' and @type = 'file' and @name = 'qqfile']</value>
      <webElementGuid>0d71b641-ac3f-4169-93f5-ee6045170597</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
