<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Absensi New</name>
   <tag></tag>
   <elementGuidId>9e907d20-b7f2-4f66-ac71-a9f02aa84412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_add_new']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_add_new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edab3bae-c613-4acf-a50b-9861369282ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat btn-success btn_add_new</value>
      <webElementGuid>f0d815a7-16bc-41f7-9c38-1455109bd212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_add_new</value>
      <webElementGuid>5919a847-278e-4ef6-94dc-dffbbbdf7055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:80/cicool/administrator/absensi/add</value>
      <webElementGuid>9ae785bf-6349-4257-83de-4888ac6ebe5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Add Absensi New  (Ctrl+a)</value>
      <webElementGuid>e4dda88e-7399-4f0b-a2c9-fbe62e832534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip451639</value>
      <webElementGuid>d0134c63-9328-4240-baeb-b19f90b52ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Absensi New</value>
      <webElementGuid>8d67bd65-5849-4041-9f40-c8659f79a355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_add_new&quot;)</value>
      <webElementGuid>8fb0543c-8386-4923-981a-d67d90a4625a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_add_new']</value>
      <webElementGuid>34267cf4-2023-4773-a78f-6893402f7af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div/div/div/div/div/div/div/a</value>
      <webElementGuid>2aff2f36-ec14-41fd-9b87-89a5ae25ca33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Absensi New')]</value>
      <webElementGuid>4c3f023a-e5e0-431a-8203-73d6f6019782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absensi'])[1]/following::a[1]</value>
      <webElementGuid>113166da-c509-4517-9d18-41bb6704efe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register All'])[1]/following::a[2]</value>
      <webElementGuid>65d615b8-ad97-4ea7-802a-6cd0a84a2c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Absensi New']/parent::*</value>
      <webElementGuid>2ea9cd7b-24cc-4812-b3b9-d17b78e9cd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:80/cicool/administrator/absensi/add']</value>
      <webElementGuid>b62ab5de-b202-4708-ac2f-7b5bccb769d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>59585454-cf9a-4abd-8729-a425527c78e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_add_new' and @href = 'http://localhost:80/cicool/administrator/absensi/add' and (text() = ' Add Absensi New' or . = ' Add Absensi New')]</value>
      <webElementGuid>f3be147a-a0f4-4b79-830a-267eea44a28c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
