<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Userbiodata New</name>
   <tag></tag>
   <elementGuidId>351e3a13-069b-4f11-b76c-824829944054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_add_new']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_add_new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a73cfed6-a9a6-45a4-9af1-e204d60b9178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat btn-success btn_add_new</value>
      <webElementGuid>05444790-acb1-4d27-ab7a-73c65eb5e427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_add_new</value>
      <webElementGuid>b7e58f2c-4144-4a6e-bcc9-9b0a9c954d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:80/cicool/administrator/userbiodata/add</value>
      <webElementGuid>9d96d8b7-f94f-407a-8005-4e664efea8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Add Userbiodata New  (Ctrl+a)</value>
      <webElementGuid>ca6f0583-6cb0-4b8f-b2e0-fbe5e93eaf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip73520</value>
      <webElementGuid>be61e7b6-edc5-44d1-b0bc-1778fa3f3016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Userbiodata New</value>
      <webElementGuid>7b8ab1ec-5b35-4420-8ee3-57803cb785dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_add_new&quot;)</value>
      <webElementGuid>80c6034f-dc59-48be-bc1f-fef9b5480827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_add_new']</value>
      <webElementGuid>06393635-1290-48e0-a11b-9fa654a35d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div/div/div/div/div/div/div/a</value>
      <webElementGuid>4da81bfa-bfcb-4c6c-b91f-54b8eb1f02f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Userbiodata New')]</value>
      <webElementGuid>0bccc706-3f0a-43a8-ae33-edd0e71de298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Userbiodata'])[1]/following::a[1]</value>
      <webElementGuid>30f908ff-0de6-468c-a317-a4f5c387ac39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register All'])[1]/following::a[2]</value>
      <webElementGuid>63d25784-c9c1-409e-8320-3c7591f2d365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Userbiodata New']/parent::*</value>
      <webElementGuid>e13529cf-00e5-4d73-afc3-269fac5093d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:80/cicool/administrator/userbiodata/add']</value>
      <webElementGuid>089a18fd-6862-4b73-b6bc-650ec39c9033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>137ff068-5d40-4d12-9e2f-cdd7589026ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_add_new' and @href = 'http://localhost:80/cicool/administrator/userbiodata/add' and (text() = ' Add Userbiodata New' or . = ' Add Userbiodata New')]</value>
      <webElementGuid>f031de34-f0a4-4fe4-9f7c-f09a3d304f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
