<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_see</name>
   <tag></tag>
   <elementGuidId>73debbf1-b1f4-4831-8ada-f01a7e7bc275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tbody_crud']/tr[2]/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f83c8ce4-55c5-43cd-a6d2-a83430f13d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:80/cicool/administrator/userbiodata</value>
      <webElementGuid>3e23c505-2535-44f7-980c-615db39dab86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-default</value>
      <webElementGuid>944eb1bb-53b2-4447-81b3-7092161ff775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> see                                                                                           </value>
      <webElementGuid>3beaafd5-1f98-46ab-b3eb-87d9fa908e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbody_crud&quot;)/tr[2]/td[5]/a[@class=&quot;label-default&quot;]</value>
      <webElementGuid>1cdf5edc-c70c-4289-8bd4-26b514555a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbody_crud']/tr[2]/td[5]/a</value>
      <webElementGuid>7d78006a-4af1-481e-abd7-f6f80454d4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'see')])[2]</value>
      <webElementGuid>300c477c-7c68-44e1-b5a8-1442b2c1c717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='userbiodata'])[1]/following::a[1]</value>
      <webElementGuid>34ac346d-a493-40f7-bf26-0d30198d538b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Userbiodata'])[2]/following::a[1]</value>
      <webElementGuid>aa2e799a-2926-4885-ab13-d2cf55ae8aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[2]/preceding::a[1]</value>
      <webElementGuid>9a558414-b3e8-4d6d-9f2b-508502e5d55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::a[2]</value>
      <webElementGuid>e3d238b4-936f-48f0-8fc3-97811d0d6a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:80/cicool/administrator/userbiodata']</value>
      <webElementGuid>fbb52c3d-81c6-4a22-b1d7-9306251ec211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/a</value>
      <webElementGuid>a46522a9-9482-43ae-bc67-ee27a5f573a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:80/cicool/administrator/userbiodata' and (text() = ' see                                                                                           ' or . = ' see                                                                                           ')]</value>
      <webElementGuid>a6dff6e6-0c8b-464d-9edb-1a4e5c266a30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
