<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save and go to list</name>
   <tag></tag>
   <elementGuidId>96e4d34b-b567-47d9-ae9b-9e46b3d5e75d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0422c90e-58b2-40ad-8258-7cd949df840b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat btn-info btn_save btn_action btn_save_back</value>
      <webElementGuid>7a218f2a-1d69-4413-b93e-7bd28b742638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_save</value>
      <webElementGuid>01a403ef-070a-418a-bb58-91faa4283749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stype</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>688f2b36-afa8-4ce7-b0d9-cd90a4f05a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Save and go to list (Ctrl+d)</value>
      <webElementGuid>ec006fbb-e4cc-4023-a8c9-6194cef724a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip404276</value>
      <webElementGuid>5aa8647d-0535-416a-903c-ef68e047399b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Save and go to list                            </value>
      <webElementGuid>d04d6b0b-131f-414b-86ad-31601359dbe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_absensi&quot;)/div[@class=&quot;row-fluid col-md-7 container-button-bottom&quot;]/a[@id=&quot;btn_save&quot;]</value>
      <webElementGuid>c6b22ecd-13ed-4eb9-8344-402932caa7b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_save']</value>
      <webElementGuid>1839d08e-c7b4-4543-8032-b3e2ead74275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_absensi']/div[5]/a</value>
      <webElementGuid>e3a369bf-24e2-4ee5-930a-7121c07ef9ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Location'])[1]/following::a[1]</value>
      <webElementGuid>a4fe1edb-3b5a-489e-bb37-ec6b75c474b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and go to list (Ctrl+d)'])[1]/preceding::a[1]</value>
      <webElementGuid>49025688-adeb-412a-a715-38fa42e04f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save and go to list']/parent::*</value>
      <webElementGuid>36c268be-fc87-42c7-9ed6-3c5538913a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>0006e3dc-3fce-45af-94ea-ce6ce41009f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_save' and (text() = '
                                 Save and go to list                            ' or . = '
                                 Save and go to list                            ')]</value>
      <webElementGuid>119048e7-de97-4bec-9afc-ee2396080e2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
